/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window_admin (void);
GtkWidget* create_liste_agents (void);
GtkWidget* create_ajout_agents (void);
GtkWidget* create_modifier_agents (void);
GtkWidget* create_supprimer_agents (void);
GtkWidget* create_liste_clients (void);
GtkWidget* create_ajout_client (void);
GtkWidget* create_modifier_clients (void);
GtkWidget* create_supprimer_clients (void);
GtkWidget* create_login (void);
