/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window_admin (void)
{
  GtkWidget *window_admin;
  GtkWidget *fixed74;
  GtkWidget *frame4;
  GtkWidget *alignment37;
  GtkWidget *fixed75;
  GtkWidget *supprimer_a;
  GtkWidget *alignment40;
  GtkWidget *hbox35;
  GtkWidget *image39;
  GtkWidget *label330;
  GtkWidget *modifier_a;
  GtkWidget *alignment41;
  GtkWidget *hbox36;
  GtkWidget *image40;
  GtkWidget *label331;
  GtkWidget *ajout_a;
  GtkWidget *alignment42;
  GtkWidget *hbox37;
  GtkWidget *image41;
  GtkWidget *label332;
  GtkWidget *liste_a;
  GtkWidget *alignment43;
  GtkWidget *hbox38;
  GtkWidget *image42;
  GtkWidget *label333;
  GtkWidget *label327;
  GtkWidget *frame5;
  GtkWidget *alignment38;
  GtkWidget *fixed76;
  GtkWidget *supprimer_c;
  GtkWidget *alignment47;
  GtkWidget *hbox42;
  GtkWidget *image46;
  GtkWidget *label337;
  GtkWidget *modifier_c;
  GtkWidget *alignment46;
  GtkWidget *hbox41;
  GtkWidget *image45;
  GtkWidget *label336;
  GtkWidget *ajout_c;
  GtkWidget *alignment45;
  GtkWidget *hbox40;
  GtkWidget *image44;
  GtkWidget *label335;
  GtkWidget *liste_c;
  GtkWidget *alignment44;
  GtkWidget *hbox39;
  GtkWidget *image43;
  GtkWidget *label334;
  GtkWidget *label328;
  GtkWidget *logout_admin;
  GtkWidget *alignment39;
  GtkWidget *hbox34;
  GtkWidget *image38;
  GtkWidget *label329;

  window_admin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window_admin), _("window admin"));

  fixed74 = gtk_fixed_new ();
  gtk_widget_show (fixed74);
  gtk_container_add (GTK_CONTAINER (window_admin), fixed74);

  frame4 = gtk_frame_new (NULL);
  gtk_widget_show (frame4);
  gtk_fixed_put (GTK_FIXED (fixed74), frame4, 80, 88);
  gtk_widget_set_size_request (frame4, 328, 272);
  gtk_container_set_border_width (GTK_CONTAINER (frame4), 3);
  gtk_frame_set_shadow_type (GTK_FRAME (frame4), GTK_SHADOW_OUT);

  alignment37 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment37);
  gtk_container_add (GTK_CONTAINER (frame4), alignment37);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment37), 0, 0, 12, 0);

  fixed75 = gtk_fixed_new ();
  gtk_widget_show (fixed75);
  gtk_container_add (GTK_CONTAINER (alignment37), fixed75);

  supprimer_a = gtk_button_new ();
  gtk_widget_show (supprimer_a);
  gtk_fixed_put (GTK_FIXED (fixed75), supprimer_a, 24, 160);
  gtk_widget_set_size_request (supprimer_a, 248, 29);

  alignment40 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment40);
  gtk_container_add (GTK_CONTAINER (supprimer_a), alignment40);

  hbox35 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox35);
  gtk_container_add (GTK_CONTAINER (alignment40), hbox35);

  image39 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image39);
  gtk_box_pack_start (GTK_BOX (hbox35), image39, FALSE, FALSE, 0);

  label330 = gtk_label_new_with_mnemonic (_("Supprimer un agent"));
  gtk_widget_show (label330);
  gtk_box_pack_start (GTK_BOX (hbox35), label330, FALSE, FALSE, 0);

  modifier_a = gtk_button_new ();
  gtk_widget_show (modifier_a);
  gtk_fixed_put (GTK_FIXED (fixed75), modifier_a, 24, 112);
  gtk_widget_set_size_request (modifier_a, 248, 29);

  alignment41 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment41);
  gtk_container_add (GTK_CONTAINER (modifier_a), alignment41);

  hbox36 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox36);
  gtk_container_add (GTK_CONTAINER (alignment41), hbox36);

  image40 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image40);
  gtk_box_pack_start (GTK_BOX (hbox36), image40, FALSE, FALSE, 0);

  label331 = gtk_label_new_with_mnemonic (_("Modifier un agent"));
  gtk_widget_show (label331);
  gtk_box_pack_start (GTK_BOX (hbox36), label331, FALSE, FALSE, 0);

  ajout_a = gtk_button_new ();
  gtk_widget_show (ajout_a);
  gtk_fixed_put (GTK_FIXED (fixed75), ajout_a, 24, 64);
  gtk_widget_set_size_request (ajout_a, 248, 29);

  alignment42 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment42);
  gtk_container_add (GTK_CONTAINER (ajout_a), alignment42);

  hbox37 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox37);
  gtk_container_add (GTK_CONTAINER (alignment42), hbox37);

  image41 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image41);
  gtk_box_pack_start (GTK_BOX (hbox37), image41, FALSE, FALSE, 0);

  label332 = gtk_label_new_with_mnemonic (_("Ajouter un agent"));
  gtk_widget_show (label332);
  gtk_box_pack_start (GTK_BOX (hbox37), label332, FALSE, FALSE, 0);

  liste_a = gtk_button_new ();
  gtk_widget_show (liste_a);
  gtk_fixed_put (GTK_FIXED (fixed75), liste_a, 24, 24);
  gtk_widget_set_size_request (liste_a, 248, 29);

  alignment43 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment43);
  gtk_container_add (GTK_CONTAINER (liste_a), alignment43);

  hbox38 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox38);
  gtk_container_add (GTK_CONTAINER (alignment43), hbox38);

  image42 = gtk_image_new_from_stock ("gtk-index", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image42);
  gtk_box_pack_start (GTK_BOX (hbox38), image42, FALSE, FALSE, 0);

  label333 = gtk_label_new_with_mnemonic (_("Liste des Agents"));
  gtk_widget_show (label333);
  gtk_box_pack_start (GTK_BOX (hbox38), label333, FALSE, FALSE, 0);

  label327 = gtk_label_new (_("<b>Gestions des Agents</b>"));
  gtk_widget_show (label327);
  gtk_frame_set_label_widget (GTK_FRAME (frame4), label327);
  gtk_label_set_use_markup (GTK_LABEL (label327), TRUE);

  frame5 = gtk_frame_new (NULL);
  gtk_widget_show (frame5);
  gtk_fixed_put (GTK_FIXED (fixed74), frame5, 480, 88);
  gtk_widget_set_size_request (frame5, 328, 272);
  gtk_container_set_border_width (GTK_CONTAINER (frame5), 3);
  gtk_frame_set_shadow_type (GTK_FRAME (frame5), GTK_SHADOW_OUT);

  alignment38 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment38);
  gtk_container_add (GTK_CONTAINER (frame5), alignment38);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment38), 0, 0, 12, 0);

  fixed76 = gtk_fixed_new ();
  gtk_widget_show (fixed76);
  gtk_container_add (GTK_CONTAINER (alignment38), fixed76);

  supprimer_c = gtk_button_new ();
  gtk_widget_show (supprimer_c);
  gtk_fixed_put (GTK_FIXED (fixed76), supprimer_c, 24, 160);
  gtk_widget_set_size_request (supprimer_c, 248, 29);

  alignment47 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment47);
  gtk_container_add (GTK_CONTAINER (supprimer_c), alignment47);

  hbox42 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox42);
  gtk_container_add (GTK_CONTAINER (alignment47), hbox42);

  image46 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image46);
  gtk_box_pack_start (GTK_BOX (hbox42), image46, FALSE, FALSE, 0);

  label337 = gtk_label_new_with_mnemonic (_("Supprimer un Client"));
  gtk_widget_show (label337);
  gtk_box_pack_start (GTK_BOX (hbox42), label337, FALSE, FALSE, 0);

  modifier_c = gtk_button_new ();
  gtk_widget_show (modifier_c);
  gtk_fixed_put (GTK_FIXED (fixed76), modifier_c, 24, 112);
  gtk_widget_set_size_request (modifier_c, 248, 29);

  alignment46 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment46);
  gtk_container_add (GTK_CONTAINER (modifier_c), alignment46);

  hbox41 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox41);
  gtk_container_add (GTK_CONTAINER (alignment46), hbox41);

  image45 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image45);
  gtk_box_pack_start (GTK_BOX (hbox41), image45, FALSE, FALSE, 0);

  label336 = gtk_label_new_with_mnemonic (_("Modifier un Client"));
  gtk_widget_show (label336);
  gtk_box_pack_start (GTK_BOX (hbox41), label336, FALSE, FALSE, 0);

  ajout_c = gtk_button_new ();
  gtk_widget_show (ajout_c);
  gtk_fixed_put (GTK_FIXED (fixed76), ajout_c, 24, 64);
  gtk_widget_set_size_request (ajout_c, 248, 29);

  alignment45 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment45);
  gtk_container_add (GTK_CONTAINER (ajout_c), alignment45);

  hbox40 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox40);
  gtk_container_add (GTK_CONTAINER (alignment45), hbox40);

  image44 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image44);
  gtk_box_pack_start (GTK_BOX (hbox40), image44, FALSE, FALSE, 0);

  label335 = gtk_label_new_with_mnemonic (_("Ajouter un Client"));
  gtk_widget_show (label335);
  gtk_box_pack_start (GTK_BOX (hbox40), label335, FALSE, FALSE, 0);

  liste_c = gtk_button_new ();
  gtk_widget_show (liste_c);
  gtk_fixed_put (GTK_FIXED (fixed76), liste_c, 24, 24);
  gtk_widget_set_size_request (liste_c, 248, 29);

  alignment44 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment44);
  gtk_container_add (GTK_CONTAINER (liste_c), alignment44);

  hbox39 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox39);
  gtk_container_add (GTK_CONTAINER (alignment44), hbox39);

  image43 = gtk_image_new_from_stock ("gtk-index", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image43);
  gtk_box_pack_start (GTK_BOX (hbox39), image43, FALSE, FALSE, 0);

  label334 = gtk_label_new_with_mnemonic (_("Liste des Clients"));
  gtk_widget_show (label334);
  gtk_box_pack_start (GTK_BOX (hbox39), label334, FALSE, FALSE, 0);

  label328 = gtk_label_new (_("<b>Gestions des Clients</b>"));
  gtk_widget_show (label328);
  gtk_frame_set_label_widget (GTK_FRAME (frame5), label328);
  gtk_label_set_use_markup (GTK_LABEL (label328), TRUE);

  logout_admin = gtk_button_new ();
  gtk_widget_show (logout_admin);
  gtk_fixed_put (GTK_FIXED (fixed74), logout_admin, 744, 400);
  gtk_widget_set_size_request (logout_admin, 96, 37);

  alignment39 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment39);
  gtk_container_add (GTK_CONTAINER (logout_admin), alignment39);

  hbox34 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox34);
  gtk_container_add (GTK_CONTAINER (alignment39), hbox34);

  image38 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image38);
  gtk_box_pack_start (GTK_BOX (hbox34), image38, FALSE, FALSE, 0);

  label329 = gtk_label_new_with_mnemonic (_("LOGOUT"));
  gtk_widget_show (label329);
  gtk_box_pack_start (GTK_BOX (hbox34), label329, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) supprimer_a, "clicked",
                    G_CALLBACK (on_supprimer_a_clicked),
                    NULL);
  g_signal_connect ((gpointer) modifier_a, "clicked",
                    G_CALLBACK (on_modifier_a_clicked),
                    NULL);
  g_signal_connect ((gpointer) ajout_a, "clicked",
                    G_CALLBACK (on_ajout_a_clicked),
                    NULL);
  g_signal_connect ((gpointer) liste_a, "clicked",
                    G_CALLBACK (on_liste_a_clicked),
                    NULL);
  g_signal_connect ((gpointer) supprimer_c, "clicked",
                    G_CALLBACK (on_supprimer_c_clicked),
                    NULL);
  g_signal_connect ((gpointer) modifier_c, "clicked",
                    G_CALLBACK (on_modifier_c_clicked),
                    NULL);
  g_signal_connect ((gpointer) ajout_c, "clicked",
                    G_CALLBACK (on_ajout_c_clicked),
                    NULL);
  g_signal_connect ((gpointer) liste_c, "clicked",
                    G_CALLBACK (on_liste_c_clicked),
                    NULL);
  g_signal_connect_swapped ((gpointer) logout_admin, "clicked",
                            G_CALLBACK (gtk_widget_hide),
                            GTK_OBJECT (window_admin));
  g_signal_connect_swapped ((gpointer) logout_admin, "clicked",
                            G_CALLBACK (gtk_widget_show),
                            GTK_OBJECT (login));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_admin, window_admin, "window_admin");
  GLADE_HOOKUP_OBJECT (window_admin, fixed74, "fixed74");
  GLADE_HOOKUP_OBJECT (window_admin, frame4, "frame4");
  GLADE_HOOKUP_OBJECT (window_admin, alignment37, "alignment37");
  GLADE_HOOKUP_OBJECT (window_admin, fixed75, "fixed75");
  GLADE_HOOKUP_OBJECT (window_admin, supprimer_a, "supprimer_a");
  GLADE_HOOKUP_OBJECT (window_admin, alignment40, "alignment40");
  GLADE_HOOKUP_OBJECT (window_admin, hbox35, "hbox35");
  GLADE_HOOKUP_OBJECT (window_admin, image39, "image39");
  GLADE_HOOKUP_OBJECT (window_admin, label330, "label330");
  GLADE_HOOKUP_OBJECT (window_admin, modifier_a, "modifier_a");
  GLADE_HOOKUP_OBJECT (window_admin, alignment41, "alignment41");
  GLADE_HOOKUP_OBJECT (window_admin, hbox36, "hbox36");
  GLADE_HOOKUP_OBJECT (window_admin, image40, "image40");
  GLADE_HOOKUP_OBJECT (window_admin, label331, "label331");
  GLADE_HOOKUP_OBJECT (window_admin, ajout_a, "ajout_a");
  GLADE_HOOKUP_OBJECT (window_admin, alignment42, "alignment42");
  GLADE_HOOKUP_OBJECT (window_admin, hbox37, "hbox37");
  GLADE_HOOKUP_OBJECT (window_admin, image41, "image41");
  GLADE_HOOKUP_OBJECT (window_admin, label332, "label332");
  GLADE_HOOKUP_OBJECT (window_admin, liste_a, "liste_a");
  GLADE_HOOKUP_OBJECT (window_admin, alignment43, "alignment43");
  GLADE_HOOKUP_OBJECT (window_admin, hbox38, "hbox38");
  GLADE_HOOKUP_OBJECT (window_admin, image42, "image42");
  GLADE_HOOKUP_OBJECT (window_admin, label333, "label333");
  GLADE_HOOKUP_OBJECT (window_admin, label327, "label327");
  GLADE_HOOKUP_OBJECT (window_admin, frame5, "frame5");
  GLADE_HOOKUP_OBJECT (window_admin, alignment38, "alignment38");
  GLADE_HOOKUP_OBJECT (window_admin, fixed76, "fixed76");
  GLADE_HOOKUP_OBJECT (window_admin, supprimer_c, "supprimer_c");
  GLADE_HOOKUP_OBJECT (window_admin, alignment47, "alignment47");
  GLADE_HOOKUP_OBJECT (window_admin, hbox42, "hbox42");
  GLADE_HOOKUP_OBJECT (window_admin, image46, "image46");
  GLADE_HOOKUP_OBJECT (window_admin, label337, "label337");
  GLADE_HOOKUP_OBJECT (window_admin, modifier_c, "modifier_c");
  GLADE_HOOKUP_OBJECT (window_admin, alignment46, "alignment46");
  GLADE_HOOKUP_OBJECT (window_admin, hbox41, "hbox41");
  GLADE_HOOKUP_OBJECT (window_admin, image45, "image45");
  GLADE_HOOKUP_OBJECT (window_admin, label336, "label336");
  GLADE_HOOKUP_OBJECT (window_admin, ajout_c, "ajout_c");
  GLADE_HOOKUP_OBJECT (window_admin, alignment45, "alignment45");
  GLADE_HOOKUP_OBJECT (window_admin, hbox40, "hbox40");
  GLADE_HOOKUP_OBJECT (window_admin, image44, "image44");
  GLADE_HOOKUP_OBJECT (window_admin, label335, "label335");
  GLADE_HOOKUP_OBJECT (window_admin, liste_c, "liste_c");
  GLADE_HOOKUP_OBJECT (window_admin, alignment44, "alignment44");
  GLADE_HOOKUP_OBJECT (window_admin, hbox39, "hbox39");
  GLADE_HOOKUP_OBJECT (window_admin, image43, "image43");
  GLADE_HOOKUP_OBJECT (window_admin, label334, "label334");
  GLADE_HOOKUP_OBJECT (window_admin, label328, "label328");
  GLADE_HOOKUP_OBJECT (window_admin, logout_admin, "logout_admin");
  GLADE_HOOKUP_OBJECT (window_admin, alignment39, "alignment39");
  GLADE_HOOKUP_OBJECT (window_admin, hbox34, "hbox34");
  GLADE_HOOKUP_OBJECT (window_admin, image38, "image38");
  GLADE_HOOKUP_OBJECT (window_admin, label329, "label329");

  return window_admin;
}

GtkWidget*
create_liste_agents (void)
{
  GtkWidget *liste_agents;
  GtkWidget *fixed66;
  GtkWidget *frame1;
  GtkWidget *alignment34;
  GtkWidget *scrolledwindow2;
  GtkWidget *treeview32;
  GtkWidget *label324;
  GtkWidget *button70;
  GtkWidget *alignment51;
  GtkWidget *hbox45;
  GtkWidget *image49;
  GtkWidget *label343;

  liste_agents = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (liste_agents), _("Liste Agents"));
  gtk_window_set_position (GTK_WINDOW (liste_agents), GTK_WIN_POS_CENTER);

  fixed66 = gtk_fixed_new ();
  gtk_widget_show (fixed66);
  gtk_container_add (GTK_CONTAINER (liste_agents), fixed66);

  frame1 = gtk_frame_new (NULL);
  gtk_widget_show (frame1);
  gtk_fixed_put (GTK_FIXED (fixed66), frame1, 80, 72);
  gtk_widget_set_size_request (frame1, 688, 312);
  gtk_container_set_border_width (GTK_CONTAINER (frame1), 2);
  gtk_frame_set_shadow_type (GTK_FRAME (frame1), GTK_SHADOW_OUT);

  alignment34 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment34);
  gtk_container_add (GTK_CONTAINER (frame1), alignment34);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment34), 0, 0, 12, 0);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow2);
  gtk_container_add (GTK_CONTAINER (alignment34), scrolledwindow2);

  treeview32 = gtk_tree_view_new ();
  gtk_widget_show (treeview32);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), treeview32);
  gtk_widget_set_size_request (treeview32, 712, 264);

  label324 = gtk_label_new (_("<b>Liste Agents:</b>"));
  gtk_widget_show (label324);
  gtk_frame_set_label_widget (GTK_FRAME (frame1), label324);
  gtk_label_set_use_markup (GTK_LABEL (label324), TRUE);

  button70 = gtk_button_new ();
  gtk_widget_show (button70);
  gtk_fixed_put (GTK_FIXED (fixed66), button70, 720, 400);
  gtk_widget_set_size_request (button70, 74, 29);

  alignment51 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment51);
  gtk_container_add (GTK_CONTAINER (button70), alignment51);

  hbox45 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox45);
  gtk_container_add (GTK_CONTAINER (alignment51), hbox45);

  image49 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image49);
  gtk_box_pack_start (GTK_BOX (hbox45), image49, FALSE, FALSE, 0);

  label343 = gtk_label_new_with_mnemonic (_("BACK"));
  gtk_widget_show (label343);
  gtk_box_pack_start (GTK_BOX (hbox45), label343, FALSE, FALSE, 0);

  g_signal_connect_swapped ((gpointer) button70, "clicked",
                            G_CALLBACK (gtk_widget_hide),
                            GTK_OBJECT (liste_agents));
  g_signal_connect_swapped ((gpointer) button70, "clicked",
                            G_CALLBACK (gtk_widget_show),
                            GTK_OBJECT (window_admin));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (liste_agents, liste_agents, "liste_agents");
  GLADE_HOOKUP_OBJECT (liste_agents, fixed66, "fixed66");
  GLADE_HOOKUP_OBJECT (liste_agents, frame1, "frame1");
  GLADE_HOOKUP_OBJECT (liste_agents, alignment34, "alignment34");
  GLADE_HOOKUP_OBJECT (liste_agents, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (liste_agents, treeview32, "treeview32");
  GLADE_HOOKUP_OBJECT (liste_agents, label324, "label324");
  GLADE_HOOKUP_OBJECT (liste_agents, button70, "button70");
  GLADE_HOOKUP_OBJECT (liste_agents, alignment51, "alignment51");
  GLADE_HOOKUP_OBJECT (liste_agents, hbox45, "hbox45");
  GLADE_HOOKUP_OBJECT (liste_agents, image49, "image49");
  GLADE_HOOKUP_OBJECT (liste_agents, label343, "label343");

  return liste_agents;
}

GtkWidget*
create_ajout_agents (void)
{
  GtkWidget *ajout_agents;
  GtkWidget *fixed67;
  GtkWidget *entry99;
  GtkWidget *entry100;
  GtkWidget *entry101;
  GtkWidget *entry102;
  GtkWidget *entry109;
  GtkWidget *combobox6;
  GtkWidget *label286;
  GtkWidget *label283;
  GtkWidget *label284;
  GtkObject *spinbutton15_adj;
  GtkWidget *spinbutton15;
  GtkWidget *label275;
  GtkWidget *label274;
  GtkWidget *label287;
  GtkWidget *calendar12;
  GtkWidget *ajouter;
  GtkWidget *alignment28;
  GtkWidget *hbox28;
  GtkWidget *image32;
  GtkWidget *label289;
  GtkWidget *label273;
  GtkWidget *button71;
  GtkWidget *alignment52;
  GtkWidget *hbox46;
  GtkWidget *image50;
  GtkWidget *label344;
  GtkWidget *label288;
  GtkWidget *label297;

  ajout_agents = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ajout_agents), _("Ajouter Agent"));
  gtk_window_set_position (GTK_WINDOW (ajout_agents), GTK_WIN_POS_CENTER);

  fixed67 = gtk_fixed_new ();
  gtk_widget_show (fixed67);
  gtk_container_add (GTK_CONTAINER (ajout_agents), fixed67);

  entry99 = gtk_entry_new ();
  gtk_widget_show (entry99);
  gtk_fixed_put (GTK_FIXED (fixed67), entry99, 216, 32);
  gtk_widget_set_size_request (entry99, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry99), 8226);

  entry100 = gtk_entry_new ();
  gtk_widget_show (entry100);
  gtk_fixed_put (GTK_FIXED (fixed67), entry100, 216, 64);
  gtk_widget_set_size_request (entry100, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry100), 8226);

  entry101 = gtk_entry_new ();
  gtk_widget_show (entry101);
  gtk_fixed_put (GTK_FIXED (fixed67), entry101, 216, 96);
  gtk_widget_set_size_request (entry101, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry101), 8226);

  entry102 = gtk_entry_new ();
  gtk_widget_show (entry102);
  gtk_fixed_put (GTK_FIXED (fixed67), entry102, 544, 24);
  gtk_widget_set_size_request (entry102, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry102), 8226);

  entry109 = gtk_entry_new ();
  gtk_widget_show (entry109);
  gtk_fixed_put (GTK_FIXED (fixed67), entry109, 544, 64);
  gtk_widget_set_size_request (entry109, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry109), 8226);

  combobox6 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox6);
  gtk_fixed_put (GTK_FIXED (fixed67), combobox6, 216, 128);
  gtk_widget_set_size_request (combobox6, 121, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6), _("HOMME"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6), _("FEMME"));

  label286 = gtk_label_new (_("Sexe"));
  gtk_widget_show (label286);
  gtk_fixed_put (GTK_FIXED (fixed67), label286, 128, 136);
  gtk_widget_set_size_request (label286, 57, 17);

  label283 = gtk_label_new (_("LOGIN"));
  gtk_widget_show (label283);
  gtk_fixed_put (GTK_FIXED (fixed67), label283, 480, 32);
  gtk_widget_set_size_request (label283, 57, 17);

  label284 = gtk_label_new (_("PASSWORD"));
  gtk_widget_show (label284);
  gtk_fixed_put (GTK_FIXED (fixed67), label284, 440, 72);
  gtk_widget_set_size_request (label284, 113, 16);

  spinbutton15_adj = gtk_adjustment_new (1, 18, 100, 1, 10, 10);
  spinbutton15 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton15_adj), 1, 0);
  gtk_widget_show (spinbutton15);
  gtk_fixed_put (GTK_FIXED (fixed67), spinbutton15, 216, 176);
  gtk_widget_set_size_request (spinbutton15, 60, 27);

  label275 = gtk_label_new (_("CIN"));
  gtk_widget_show (label275);
  gtk_fixed_put (GTK_FIXED (fixed67), label275, 136, 104);
  gtk_widget_set_size_request (label275, 57, 17);

  label274 = gtk_label_new (_("PRENOM"));
  gtk_widget_show (label274);
  gtk_fixed_put (GTK_FIXED (fixed67), label274, 120, 72);
  gtk_widget_set_size_request (label274, 80, 16);

  label287 = gtk_label_new (_("Age"));
  gtk_widget_show (label287);
  gtk_fixed_put (GTK_FIXED (fixed67), label287, 136, 184);
  gtk_widget_set_size_request (label287, 57, 17);
  gtk_misc_set_alignment (GTK_MISC (label287), 0.5, 0.48);

  calendar12 = gtk_calendar_new ();
  gtk_widget_show (calendar12);
  gtk_fixed_put (GTK_FIXED (fixed67), calendar12, 544, 160);
  gtk_widget_set_size_request (calendar12, 253, 184);
  gtk_calendar_display_options (GTK_CALENDAR (calendar12),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  ajouter = gtk_button_new ();
  gtk_widget_show (ajouter);
  gtk_fixed_put (GTK_FIXED (fixed67), ajouter, 248, 280);
  gtk_widget_set_size_request (ajouter, 88, 29);

  alignment28 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment28);
  gtk_container_add (GTK_CONTAINER (ajouter), alignment28);

  hbox28 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox28);
  gtk_container_add (GTK_CONTAINER (alignment28), hbox28);

  image32 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image32);
  gtk_box_pack_start (GTK_BOX (hbox28), image32, FALSE, FALSE, 0);

  label289 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label289);
  gtk_box_pack_start (GTK_BOX (hbox28), label289, FALSE, FALSE, 0);

  label273 = gtk_label_new (_("NOM"));
  gtk_widget_show (label273);
  gtk_fixed_put (GTK_FIXED (fixed67), label273, 120, 40);
  gtk_widget_set_size_request (label273, 56, 16);

  button71 = gtk_button_new ();
  gtk_widget_show (button71);
  gtk_fixed_put (GTK_FIXED (fixed67), button71, 704, 416);
  gtk_widget_set_size_request (button71, 74, 29);

  alignment52 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment52);
  gtk_container_add (GTK_CONTAINER (button71), alignment52);

  hbox46 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox46);
  gtk_container_add (GTK_CONTAINER (alignment52), hbox46);

  image50 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image50);
  gtk_box_pack_start (GTK_BOX (hbox46), image50, FALSE, FALSE, 0);

  label344 = gtk_label_new_with_mnemonic (_("Back"));
  gtk_widget_show (label344);
  gtk_box_pack_start (GTK_BOX (hbox46), label344, FALSE, FALSE, 0);

  label288 = gtk_label_new (_("Date de recrutement:"));
  gtk_widget_show (label288);
  gtk_fixed_put (GTK_FIXED (fixed67), label288, 592, 128);
  gtk_widget_set_size_request (label288, 168, 16);

  label297 = gtk_label_new ("");
  gtk_widget_show (label297);
  gtk_fixed_put (GTK_FIXED (fixed67), label297, 168, 240);
  gtk_widget_set_size_request (label297, 256, 41);

  g_signal_connect ((gpointer) ajouter, "clicked",
                    G_CALLBACK (on_ajouter_clicked),
                    NULL);
  g_signal_connect_swapped ((gpointer) button71, "clicked",
                            G_CALLBACK (gtk_widget_hide),
                            GTK_OBJECT (ajout_agents));
  g_signal_connect_swapped ((gpointer) button71, "clicked",
                            G_CALLBACK (gtk_widget_show),
                            GTK_OBJECT (window_admin));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajout_agents, ajout_agents, "ajout_agents");
  GLADE_HOOKUP_OBJECT (ajout_agents, fixed67, "fixed67");
  GLADE_HOOKUP_OBJECT (ajout_agents, entry99, "entry99");
  GLADE_HOOKUP_OBJECT (ajout_agents, entry100, "entry100");
  GLADE_HOOKUP_OBJECT (ajout_agents, entry101, "entry101");
  GLADE_HOOKUP_OBJECT (ajout_agents, entry102, "entry102");
  GLADE_HOOKUP_OBJECT (ajout_agents, entry109, "entry109");
  GLADE_HOOKUP_OBJECT (ajout_agents, combobox6, "combobox6");
  GLADE_HOOKUP_OBJECT (ajout_agents, label286, "label286");
  GLADE_HOOKUP_OBJECT (ajout_agents, label283, "label283");
  GLADE_HOOKUP_OBJECT (ajout_agents, label284, "label284");
  GLADE_HOOKUP_OBJECT (ajout_agents, spinbutton15, "spinbutton15");
  GLADE_HOOKUP_OBJECT (ajout_agents, label275, "label275");
  GLADE_HOOKUP_OBJECT (ajout_agents, label274, "label274");
  GLADE_HOOKUP_OBJECT (ajout_agents, label287, "label287");
  GLADE_HOOKUP_OBJECT (ajout_agents, calendar12, "calendar12");
  GLADE_HOOKUP_OBJECT (ajout_agents, ajouter, "ajouter");
  GLADE_HOOKUP_OBJECT (ajout_agents, alignment28, "alignment28");
  GLADE_HOOKUP_OBJECT (ajout_agents, hbox28, "hbox28");
  GLADE_HOOKUP_OBJECT (ajout_agents, image32, "image32");
  GLADE_HOOKUP_OBJECT (ajout_agents, label289, "label289");
  GLADE_HOOKUP_OBJECT (ajout_agents, label273, "label273");
  GLADE_HOOKUP_OBJECT (ajout_agents, button71, "button71");
  GLADE_HOOKUP_OBJECT (ajout_agents, alignment52, "alignment52");
  GLADE_HOOKUP_OBJECT (ajout_agents, hbox46, "hbox46");
  GLADE_HOOKUP_OBJECT (ajout_agents, image50, "image50");
  GLADE_HOOKUP_OBJECT (ajout_agents, label344, "label344");
  GLADE_HOOKUP_OBJECT (ajout_agents, label288, "label288");
  GLADE_HOOKUP_OBJECT (ajout_agents, label297, "label297");

  return ajout_agents;
}

GtkWidget*
create_modifier_agents (void)
{
  GtkWidget *modifier_agents;
  GtkWidget *fixed68;
  GtkWidget *entry104;
  GtkWidget *entry106;
  GtkWidget *entry107;
  GtkWidget *entry110;
  GtkWidget *label278;
  GtkWidget *label279;
  GtkWidget *label285;
  GtkWidget *label281;
  GtkObject *spinbutton16_adj;
  GtkWidget *spinbutton16;
  GtkWidget *label292;
  GtkWidget *label280;
  GtkWidget *combobox7;
  GtkWidget *label293;
  GtkWidget *label295;
  GtkWidget *label296;
  GtkWidget *label294;
  GtkWidget *frame7;
  GtkWidget *alignment53;
  GtkWidget *scrolledwindow5;
  GtkWidget *treeview33;
  GtkWidget *label345;
  GtkWidget *button72;
  GtkWidget *alignment54;
  GtkWidget *hbox47;
  GtkWidget *image51;
  GtkWidget *label346;
  GtkWidget *label356;
  GtkWidget *Modifier;
  GtkWidget *alignment30;
  GtkWidget *hbox30;
  GtkWidget *image34;
  GtkWidget *label291;

  modifier_agents = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (modifier_agents), _("Modifier Agent"));
  gtk_window_set_position (GTK_WINDOW (modifier_agents), GTK_WIN_POS_CENTER);

  fixed68 = gtk_fixed_new ();
  gtk_widget_show (fixed68);
  gtk_container_add (GTK_CONTAINER (modifier_agents), fixed68);

  entry104 = gtk_entry_new ();
  gtk_widget_show (entry104);
  gtk_fixed_put (GTK_FIXED (fixed68), entry104, 648, 56);
  gtk_widget_set_size_request (entry104, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry104), 8226);

  entry106 = gtk_entry_new ();
  gtk_widget_show (entry106);
  gtk_fixed_put (GTK_FIXED (fixed68), entry106, 648, 248);
  gtk_widget_set_size_request (entry106, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry106), 8226);

  entry107 = gtk_entry_new ();
  gtk_widget_show (entry107);
  gtk_fixed_put (GTK_FIXED (fixed68), entry107, 648, 16);
  gtk_widget_set_size_request (entry107, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry107), 8226);

  entry110 = gtk_entry_new ();
  gtk_widget_show (entry110);
  gtk_fixed_put (GTK_FIXED (fixed68), entry110, 648, 280);
  gtk_widget_set_size_request (entry110, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry110), 8226);

  label278 = gtk_label_new (_("NOM"));
  gtk_widget_show (label278);
  gtk_fixed_put (GTK_FIXED (fixed68), label278, 568, 24);
  gtk_widget_set_size_request (label278, 57, 17);

  label279 = gtk_label_new (_("PRENOM"));
  gtk_widget_show (label279);
  gtk_fixed_put (GTK_FIXED (fixed68), label279, 544, 64);
  gtk_widget_set_size_request (label279, 105, 16);

  label285 = gtk_label_new (_("PASSWORD"));
  gtk_widget_show (label285);
  gtk_fixed_put (GTK_FIXED (fixed68), label285, 544, 280);
  gtk_widget_set_size_request (label285, 113, 25);

  label281 = gtk_label_new (_("LOGIN"));
  gtk_widget_show (label281);
  gtk_fixed_put (GTK_FIXED (fixed68), label281, 576, 256);
  gtk_widget_set_size_request (label281, 57, 17);

  spinbutton16_adj = gtk_adjustment_new (18, 0, 100, 1, 10, 10);
  spinbutton16 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton16_adj), 1, 0);
  gtk_widget_show (spinbutton16);
  gtk_fixed_put (GTK_FIXED (fixed68), spinbutton16, 656, 184);
  gtk_widget_set_size_request (spinbutton16, 60, 27);

  label292 = gtk_label_new (_("Sexe"));
  gtk_widget_show (label292);
  gtk_fixed_put (GTK_FIXED (fixed68), label292, 576, 144);
  gtk_widget_set_size_request (label292, 57, 17);

  label280 = gtk_label_new (_("CIN"));
  gtk_widget_show (label280);
  gtk_fixed_put (GTK_FIXED (fixed68), label280, 576, 104);
  gtk_widget_set_size_request (label280, 57, 17);

  combobox7 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox7);
  gtk_fixed_put (GTK_FIXED (fixed68), combobox7, 648, 136);
  gtk_widget_set_size_request (combobox7, 97, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox7), _("HOMME"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox7), _("FEMME"));

  label293 = gtk_label_new (_("Age"));
  gtk_widget_show (label293);
  gtk_fixed_put (GTK_FIXED (fixed68), label293, 576, 192);
  gtk_widget_set_size_request (label293, 57, 17);

  label295 = gtk_label_new ("");
  gtk_widget_show (label295);
  gtk_fixed_put (GTK_FIXED (fixed68), label295, 648, 216);
  gtk_widget_set_size_request (label295, 184, 25);

  label296 = gtk_label_new ("");
  gtk_widget_show (label296);
  gtk_fixed_put (GTK_FIXED (fixed68), label296, 648, 96);
  gtk_widget_set_size_request (label296, 152, 25);

  label294 = gtk_label_new (_("Date Recrutement"));
  gtk_widget_show (label294);
  gtk_fixed_put (GTK_FIXED (fixed68), label294, 552, 224);
  gtk_widget_set_size_request (label294, 113, 16);

  frame7 = gtk_frame_new (NULL);
  gtk_widget_show (frame7);
  gtk_fixed_put (GTK_FIXED (fixed68), frame7, 24, 32);
  gtk_widget_set_size_request (frame7, 488, 384);
  gtk_container_set_border_width (GTK_CONTAINER (frame7), 2);
  gtk_frame_set_shadow_type (GTK_FRAME (frame7), GTK_SHADOW_OUT);

  alignment53 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment53);
  gtk_container_add (GTK_CONTAINER (frame7), alignment53);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment53), 0, 0, 12, 0);

  scrolledwindow5 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow5);
  gtk_container_add (GTK_CONTAINER (alignment53), scrolledwindow5);

  treeview33 = gtk_tree_view_new ();
  gtk_widget_show (treeview33);
  gtk_container_add (GTK_CONTAINER (scrolledwindow5), treeview33);
  gtk_widget_set_size_request (treeview33, 536, 280);

  label345 = gtk_label_new (_("<b>Liste Agents:</b>"));
  gtk_widget_show (label345);
  gtk_frame_set_label_widget (GTK_FRAME (frame7), label345);
  gtk_label_set_use_markup (GTK_LABEL (label345), TRUE);

  button72 = gtk_button_new ();
  gtk_widget_show (button72);
  gtk_fixed_put (GTK_FIXED (fixed68), button72, 680, 376);
  gtk_widget_set_size_request (button72, 74, 29);

  alignment54 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment54);
  gtk_container_add (GTK_CONTAINER (button72), alignment54);

  hbox47 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox47);
  gtk_container_add (GTK_CONTAINER (alignment54), hbox47);

  image51 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image51);
  gtk_box_pack_start (GTK_BOX (hbox47), image51, FALSE, FALSE, 0);

  label346 = gtk_label_new_with_mnemonic (_("Back"));
  gtk_widget_show (label346);
  gtk_box_pack_start (GTK_BOX (hbox47), label346, FALSE, FALSE, 0);

  label356 = gtk_label_new ("");
  gtk_widget_show (label356);
  gtk_fixed_put (GTK_FIXED (fixed68), label356, 104, 8);
  gtk_widget_set_size_request (label356, 352, 25);

  Modifier = gtk_button_new ();
  gtk_fixed_put (GTK_FIXED (fixed68), Modifier, 664, 320);
  gtk_widget_set_size_request (Modifier, 96, 29);

  alignment30 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment30);
  gtk_container_add (GTK_CONTAINER (Modifier), alignment30);

  hbox30 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox30);
  gtk_container_add (GTK_CONTAINER (alignment30), hbox30);

  image34 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image34);
  gtk_box_pack_start (GTK_BOX (hbox30), image34, FALSE, FALSE, 0);

  label291 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label291);
  gtk_box_pack_start (GTK_BOX (hbox30), label291, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) treeview33, "row_activated",
                    G_CALLBACK (on_treeview33_row_activated),
                    NULL);
  g_signal_connect_swapped ((gpointer) button72, "clicked",
                            G_CALLBACK (gtk_widget_hide),
                            GTK_OBJECT (modifier_agents));
  g_signal_connect_swapped ((gpointer) button72, "clicked",
                            G_CALLBACK (gtk_widget_show),
                            GTK_OBJECT (window_admin));
  g_signal_connect ((gpointer) Modifier, "clicked",
                    G_CALLBACK (on_Modifier_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modifier_agents, modifier_agents, "modifier_agents");
  GLADE_HOOKUP_OBJECT (modifier_agents, fixed68, "fixed68");
  GLADE_HOOKUP_OBJECT (modifier_agents, entry104, "entry104");
  GLADE_HOOKUP_OBJECT (modifier_agents, entry106, "entry106");
  GLADE_HOOKUP_OBJECT (modifier_agents, entry107, "entry107");
  GLADE_HOOKUP_OBJECT (modifier_agents, entry110, "entry110");
  GLADE_HOOKUP_OBJECT (modifier_agents, label278, "label278");
  GLADE_HOOKUP_OBJECT (modifier_agents, label279, "label279");
  GLADE_HOOKUP_OBJECT (modifier_agents, label285, "label285");
  GLADE_HOOKUP_OBJECT (modifier_agents, label281, "label281");
  GLADE_HOOKUP_OBJECT (modifier_agents, spinbutton16, "spinbutton16");
  GLADE_HOOKUP_OBJECT (modifier_agents, label292, "label292");
  GLADE_HOOKUP_OBJECT (modifier_agents, label280, "label280");
  GLADE_HOOKUP_OBJECT (modifier_agents, combobox7, "combobox7");
  GLADE_HOOKUP_OBJECT (modifier_agents, label293, "label293");
  GLADE_HOOKUP_OBJECT (modifier_agents, label295, "label295");
  GLADE_HOOKUP_OBJECT (modifier_agents, label296, "label296");
  GLADE_HOOKUP_OBJECT (modifier_agents, label294, "label294");
  GLADE_HOOKUP_OBJECT (modifier_agents, frame7, "frame7");
  GLADE_HOOKUP_OBJECT (modifier_agents, alignment53, "alignment53");
  GLADE_HOOKUP_OBJECT (modifier_agents, scrolledwindow5, "scrolledwindow5");
  GLADE_HOOKUP_OBJECT (modifier_agents, treeview33, "treeview33");
  GLADE_HOOKUP_OBJECT (modifier_agents, label345, "label345");
  GLADE_HOOKUP_OBJECT (modifier_agents, button72, "button72");
  GLADE_HOOKUP_OBJECT (modifier_agents, alignment54, "alignment54");
  GLADE_HOOKUP_OBJECT (modifier_agents, hbox47, "hbox47");
  GLADE_HOOKUP_OBJECT (modifier_agents, image51, "image51");
  GLADE_HOOKUP_OBJECT (modifier_agents, label346, "label346");
  GLADE_HOOKUP_OBJECT (modifier_agents, label356, "label356");
  GLADE_HOOKUP_OBJECT (modifier_agents, Modifier, "Modifier");
  GLADE_HOOKUP_OBJECT (modifier_agents, alignment30, "alignment30");
  GLADE_HOOKUP_OBJECT (modifier_agents, hbox30, "hbox30");
  GLADE_HOOKUP_OBJECT (modifier_agents, image34, "image34");
  GLADE_HOOKUP_OBJECT (modifier_agents, label291, "label291");

  return modifier_agents;
}

GtkWidget*
create_supprimer_agents (void)
{
  GtkWidget *supprimer_agents;
  GtkWidget *fixed69;
  GtkWidget *Supprimer;
  GtkWidget *alignment29;
  GtkWidget *hbox29;
  GtkWidget *image33;
  GtkWidget *label290;
  GtkWidget *frame8;
  GtkWidget *alignment55;
  GtkWidget *scrolledwindow6;
  GtkWidget *treeview34;
  GtkWidget *label347;
  GtkWidget *button73;
  GtkWidget *alignment56;
  GtkWidget *hbox48;
  GtkWidget *image52;
  GtkWidget *label348;
  GtkWidget *label355;

  supprimer_agents = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (supprimer_agents), _("Supprimer Agent"));
  gtk_window_set_position (GTK_WINDOW (supprimer_agents), GTK_WIN_POS_CENTER);

  fixed69 = gtk_fixed_new ();
  gtk_widget_show (fixed69);
  gtk_container_add (GTK_CONTAINER (supprimer_agents), fixed69);

  Supprimer = gtk_button_new ();
  gtk_widget_show (Supprimer);
  gtk_fixed_put (GTK_FIXED (fixed69), Supprimer, 736, 112);
  gtk_widget_set_size_request (Supprimer, 104, 32);

  alignment29 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment29);
  gtk_container_add (GTK_CONTAINER (Supprimer), alignment29);

  hbox29 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox29);
  gtk_container_add (GTK_CONTAINER (alignment29), hbox29);

  image33 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image33);
  gtk_box_pack_start (GTK_BOX (hbox29), image33, FALSE, FALSE, 0);

  label290 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label290);
  gtk_box_pack_start (GTK_BOX (hbox29), label290, FALSE, FALSE, 0);

  frame8 = gtk_frame_new (NULL);
  gtk_widget_show (frame8);
  gtk_fixed_put (GTK_FIXED (fixed69), frame8, 48, 48);
  gtk_widget_set_size_request (frame8, 656, 352);
  gtk_container_set_border_width (GTK_CONTAINER (frame8), 2);
  gtk_frame_set_shadow_type (GTK_FRAME (frame8), GTK_SHADOW_OUT);

  alignment55 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment55);
  gtk_container_add (GTK_CONTAINER (frame8), alignment55);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment55), 0, 0, 12, 0);

  scrolledwindow6 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow6);
  gtk_container_add (GTK_CONTAINER (alignment55), scrolledwindow6);

  treeview34 = gtk_tree_view_new ();
  gtk_widget_show (treeview34);
  gtk_container_add (GTK_CONTAINER (scrolledwindow6), treeview34);
  gtk_widget_set_size_request (treeview34, 640, 240);

  label347 = gtk_label_new (_("<b>Liste Agents:</b>"));
  gtk_widget_show (label347);
  gtk_frame_set_label_widget (GTK_FRAME (frame8), label347);
  gtk_label_set_use_markup (GTK_LABEL (label347), TRUE);

  button73 = gtk_button_new ();
  gtk_widget_show (button73);
  gtk_fixed_put (GTK_FIXED (fixed69), button73, 752, 376);
  gtk_widget_set_size_request (button73, 74, 29);

  alignment56 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment56);
  gtk_container_add (GTK_CONTAINER (button73), alignment56);

  hbox48 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox48);
  gtk_container_add (GTK_CONTAINER (alignment56), hbox48);

  image52 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image52);
  gtk_box_pack_start (GTK_BOX (hbox48), image52, FALSE, FALSE, 0);

  label348 = gtk_label_new_with_mnemonic (_("Back"));
  gtk_widget_show (label348);
  gtk_box_pack_start (GTK_BOX (hbox48), label348, FALSE, FALSE, 0);

  label355 = gtk_label_new ("");
  gtk_widget_show (label355);
  gtk_fixed_put (GTK_FIXED (fixed69), label355, 208, 16);
  gtk_widget_set_size_request (label355, 432, 33);

  g_signal_connect ((gpointer) Supprimer, "clicked",
                    G_CALLBACK (on_Supprimer_clicked),
                    NULL);
  g_signal_connect_swapped ((gpointer) button73, "clicked",
                            G_CALLBACK (gtk_widget_hide),
                            GTK_OBJECT (supprimer_agents));
  g_signal_connect_swapped ((gpointer) button73, "clicked",
                            G_CALLBACK (gtk_widget_show),
                            GTK_OBJECT (window_admin));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (supprimer_agents, supprimer_agents, "supprimer_agents");
  GLADE_HOOKUP_OBJECT (supprimer_agents, fixed69, "fixed69");
  GLADE_HOOKUP_OBJECT (supprimer_agents, Supprimer, "Supprimer");
  GLADE_HOOKUP_OBJECT (supprimer_agents, alignment29, "alignment29");
  GLADE_HOOKUP_OBJECT (supprimer_agents, hbox29, "hbox29");
  GLADE_HOOKUP_OBJECT (supprimer_agents, image33, "image33");
  GLADE_HOOKUP_OBJECT (supprimer_agents, label290, "label290");
  GLADE_HOOKUP_OBJECT (supprimer_agents, frame8, "frame8");
  GLADE_HOOKUP_OBJECT (supprimer_agents, alignment55, "alignment55");
  GLADE_HOOKUP_OBJECT (supprimer_agents, scrolledwindow6, "scrolledwindow6");
  GLADE_HOOKUP_OBJECT (supprimer_agents, treeview34, "treeview34");
  GLADE_HOOKUP_OBJECT (supprimer_agents, label347, "label347");
  GLADE_HOOKUP_OBJECT (supprimer_agents, button73, "button73");
  GLADE_HOOKUP_OBJECT (supprimer_agents, alignment56, "alignment56");
  GLADE_HOOKUP_OBJECT (supprimer_agents, hbox48, "hbox48");
  GLADE_HOOKUP_OBJECT (supprimer_agents, image52, "image52");
  GLADE_HOOKUP_OBJECT (supprimer_agents, label348, "label348");
  GLADE_HOOKUP_OBJECT (supprimer_agents, label355, "label355");

  return supprimer_agents;
}

GtkWidget*
create_liste_clients (void)
{
  GtkWidget *liste_clients;
  GtkWidget *fixed70;
  GtkWidget *frame2;
  GtkWidget *alignment35;
  GtkWidget *scrolledwindow3;
  GtkWidget *treeview35;
  GtkWidget *label325;
  GtkWidget *button74;
  GtkWidget *alignment57;
  GtkWidget *hbox49;
  GtkWidget *image53;
  GtkWidget *label349;

  liste_clients = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (liste_clients), _("Liste Clients"));
  gtk_window_set_position (GTK_WINDOW (liste_clients), GTK_WIN_POS_CENTER);

  fixed70 = gtk_fixed_new ();
  gtk_widget_show (fixed70);
  gtk_container_add (GTK_CONTAINER (liste_clients), fixed70);

  frame2 = gtk_frame_new (NULL);
  gtk_widget_show (frame2);
  gtk_fixed_put (GTK_FIXED (fixed70), frame2, 40, 40);
  gtk_widget_set_size_request (frame2, 744, 264);
  gtk_frame_set_shadow_type (GTK_FRAME (frame2), GTK_SHADOW_NONE);

  alignment35 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment35);
  gtk_container_add (GTK_CONTAINER (frame2), alignment35);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment35), 0, 0, 12, 0);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow3);
  gtk_container_add (GTK_CONTAINER (alignment35), scrolledwindow3);

  treeview35 = gtk_tree_view_new ();
  gtk_widget_show (treeview35);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), treeview35);
  gtk_widget_set_size_request (treeview35, 712, 264);

  label325 = gtk_label_new (_("<b>Liste Clients:</b>"));
  gtk_widget_show (label325);
  gtk_frame_set_label_widget (GTK_FRAME (frame2), label325);
  gtk_label_set_use_markup (GTK_LABEL (label325), TRUE);

  button74 = gtk_button_new ();
  gtk_widget_show (button74);
  gtk_fixed_put (GTK_FIXED (fixed70), button74, 640, 368);
  gtk_widget_set_size_request (button74, 74, 29);

  alignment57 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment57);
  gtk_container_add (GTK_CONTAINER (button74), alignment57);

  hbox49 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox49);
  gtk_container_add (GTK_CONTAINER (alignment57), hbox49);

  image53 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image53);
  gtk_box_pack_start (GTK_BOX (hbox49), image53, FALSE, FALSE, 0);

  label349 = gtk_label_new_with_mnemonic (_("Back"));
  gtk_widget_show (label349);
  gtk_box_pack_start (GTK_BOX (hbox49), label349, FALSE, FALSE, 0);

  g_signal_connect_swapped ((gpointer) button74, "clicked",
                            G_CALLBACK (gtk_widget_hide),
                            GTK_OBJECT (liste_clients));
  g_signal_connect_swapped ((gpointer) button74, "clicked",
                            G_CALLBACK (gtk_widget_show),
                            GTK_OBJECT (window_admin));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (liste_clients, liste_clients, "liste_clients");
  GLADE_HOOKUP_OBJECT (liste_clients, fixed70, "fixed70");
  GLADE_HOOKUP_OBJECT (liste_clients, frame2, "frame2");
  GLADE_HOOKUP_OBJECT (liste_clients, alignment35, "alignment35");
  GLADE_HOOKUP_OBJECT (liste_clients, scrolledwindow3, "scrolledwindow3");
  GLADE_HOOKUP_OBJECT (liste_clients, treeview35, "treeview35");
  GLADE_HOOKUP_OBJECT (liste_clients, label325, "label325");
  GLADE_HOOKUP_OBJECT (liste_clients, button74, "button74");
  GLADE_HOOKUP_OBJECT (liste_clients, alignment57, "alignment57");
  GLADE_HOOKUP_OBJECT (liste_clients, hbox49, "hbox49");
  GLADE_HOOKUP_OBJECT (liste_clients, image53, "image53");
  GLADE_HOOKUP_OBJECT (liste_clients, label349, "label349");

  return liste_clients;
}

GtkWidget*
create_ajout_client (void)
{
  GtkWidget *ajout_client;
  GtkWidget *fixed71;
  GtkWidget *entry111;
  GtkWidget *entry112;
  GtkWidget *entry113;
  GtkWidget *entry114;
  GtkWidget *entry115;
  GtkWidget *label299;
  GtkWidget *label300;
  GtkWidget *label301;
  GtkWidget *label302;
  GtkObject *spinbutton17_adj;
  GtkWidget *spinbutton17;
  GtkWidget *label303;
  GtkWidget *label304;
  GtkWidget *label305;
  GtkWidget *calendar13;
  GtkWidget *label306;
  GtkWidget *button75;
  GtkWidget *alignment58;
  GtkWidget *hbox50;
  GtkWidget *image54;
  GtkWidget *label350;
  GtkWidget *ajouter_client;
  GtkWidget *alignment31;
  GtkWidget *hbox31;
  GtkWidget *image35;
  GtkWidget *label307;
  GtkWidget *label308;
  GtkWidget *combobox8;

  ajout_client = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ajout_client), _("Ajouter Client"));
  gtk_window_set_position (GTK_WINDOW (ajout_client), GTK_WIN_POS_CENTER);

  fixed71 = gtk_fixed_new ();
  gtk_widget_show (fixed71);
  gtk_container_add (GTK_CONTAINER (ajout_client), fixed71);

  entry111 = gtk_entry_new ();
  gtk_widget_show (entry111);
  gtk_fixed_put (GTK_FIXED (fixed71), entry111, 216, 32);
  gtk_widget_set_size_request (entry111, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry111), 8226);

  entry112 = gtk_entry_new ();
  gtk_widget_show (entry112);
  gtk_fixed_put (GTK_FIXED (fixed71), entry112, 216, 64);
  gtk_widget_set_size_request (entry112, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry112), 8226);

  entry113 = gtk_entry_new ();
  gtk_widget_show (entry113);
  gtk_fixed_put (GTK_FIXED (fixed71), entry113, 216, 96);
  gtk_widget_set_size_request (entry113, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry113), 8226);

  entry114 = gtk_entry_new ();
  gtk_widget_show (entry114);
  gtk_fixed_put (GTK_FIXED (fixed71), entry114, 544, 24);
  gtk_widget_set_size_request (entry114, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry114), 8226);

  entry115 = gtk_entry_new ();
  gtk_widget_show (entry115);
  gtk_fixed_put (GTK_FIXED (fixed71), entry115, 544, 64);
  gtk_widget_set_size_request (entry115, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry115), 8226);

  label299 = gtk_label_new (_("NOM"));
  gtk_widget_show (label299);
  gtk_fixed_put (GTK_FIXED (fixed71), label299, 120, 40);
  gtk_widget_set_size_request (label299, 56, 16);

  label300 = gtk_label_new (_("Sexe"));
  gtk_widget_show (label300);
  gtk_fixed_put (GTK_FIXED (fixed71), label300, 128, 136);
  gtk_widget_set_size_request (label300, 57, 17);

  label301 = gtk_label_new (_("LOGIN"));
  gtk_widget_show (label301);
  gtk_fixed_put (GTK_FIXED (fixed71), label301, 480, 32);
  gtk_widget_set_size_request (label301, 57, 17);

  label302 = gtk_label_new (_("PASSWORD"));
  gtk_widget_show (label302);
  gtk_fixed_put (GTK_FIXED (fixed71), label302, 440, 72);
  gtk_widget_set_size_request (label302, 113, 16);

  spinbutton17_adj = gtk_adjustment_new (1, 18, 100, 1, 10, 10);
  spinbutton17 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton17_adj), 1, 0);
  gtk_widget_show (spinbutton17);
  gtk_fixed_put (GTK_FIXED (fixed71), spinbutton17, 216, 176);
  gtk_widget_set_size_request (spinbutton17, 60, 27);

  label303 = gtk_label_new (_("CIN"));
  gtk_widget_show (label303);
  gtk_fixed_put (GTK_FIXED (fixed71), label303, 136, 104);
  gtk_widget_set_size_request (label303, 57, 17);

  label304 = gtk_label_new (_("PRENOM"));
  gtk_widget_show (label304);
  gtk_fixed_put (GTK_FIXED (fixed71), label304, 120, 72);
  gtk_widget_set_size_request (label304, 80, 16);

  label305 = gtk_label_new (_("Age"));
  gtk_widget_show (label305);
  gtk_fixed_put (GTK_FIXED (fixed71), label305, 136, 184);
  gtk_widget_set_size_request (label305, 57, 17);
  gtk_misc_set_alignment (GTK_MISC (label305), 0.5, 0.48);

  calendar13 = gtk_calendar_new ();
  gtk_widget_show (calendar13);
  gtk_fixed_put (GTK_FIXED (fixed71), calendar13, 544, 160);
  gtk_widget_set_size_request (calendar13, 253, 184);
  gtk_calendar_display_options (GTK_CALENDAR (calendar13),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  label306 = gtk_label_new (_("Date d'inscription"));
  gtk_widget_show (label306);
  gtk_fixed_put (GTK_FIXED (fixed71), label306, 592, 128);
  gtk_widget_set_size_request (label306, 168, 16);

  button75 = gtk_button_new ();
  gtk_widget_show (button75);
  gtk_fixed_put (GTK_FIXED (fixed71), button75, 688, 360);
  gtk_widget_set_size_request (button75, 74, 29);

  alignment58 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment58);
  gtk_container_add (GTK_CONTAINER (button75), alignment58);

  hbox50 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox50);
  gtk_container_add (GTK_CONTAINER (alignment58), hbox50);

  image54 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image54);
  gtk_box_pack_start (GTK_BOX (hbox50), image54, FALSE, FALSE, 0);

  label350 = gtk_label_new_with_mnemonic (_("Back"));
  gtk_widget_show (label350);
  gtk_box_pack_start (GTK_BOX (hbox50), label350, FALSE, FALSE, 0);

  ajouter_client = gtk_button_new ();
  gtk_widget_show (ajouter_client);
  gtk_fixed_put (GTK_FIXED (fixed71), ajouter_client, 248, 280);
  gtk_widget_set_size_request (ajouter_client, 88, 29);

  alignment31 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment31);
  gtk_container_add (GTK_CONTAINER (ajouter_client), alignment31);

  hbox31 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox31);
  gtk_container_add (GTK_CONTAINER (alignment31), hbox31);

  image35 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image35);
  gtk_box_pack_start (GTK_BOX (hbox31), image35, FALSE, FALSE, 0);

  label307 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label307);
  gtk_box_pack_start (GTK_BOX (hbox31), label307, FALSE, FALSE, 0);

  label308 = gtk_label_new ("");
  gtk_widget_show (label308);
  gtk_fixed_put (GTK_FIXED (fixed71), label308, 168, 240);
  gtk_widget_set_size_request (label308, 256, 41);

  combobox8 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox8);
  gtk_fixed_put (GTK_FIXED (fixed71), combobox8, 216, 128);
  gtk_widget_set_size_request (combobox8, 121, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox8), _("HOMME"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox8), _("FEMME"));

  g_signal_connect_swapped ((gpointer) button75, "clicked",
                            G_CALLBACK (gtk_widget_hide),
                            GTK_OBJECT (ajout_client));
  g_signal_connect_swapped ((gpointer) button75, "clicked",
                            G_CALLBACK (gtk_widget_show),
                            GTK_OBJECT (window_admin));
  g_signal_connect ((gpointer) ajouter_client, "clicked",
                    G_CALLBACK (on_ajouter_client_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajout_client, ajout_client, "ajout_client");
  GLADE_HOOKUP_OBJECT (ajout_client, fixed71, "fixed71");
  GLADE_HOOKUP_OBJECT (ajout_client, entry111, "entry111");
  GLADE_HOOKUP_OBJECT (ajout_client, entry112, "entry112");
  GLADE_HOOKUP_OBJECT (ajout_client, entry113, "entry113");
  GLADE_HOOKUP_OBJECT (ajout_client, entry114, "entry114");
  GLADE_HOOKUP_OBJECT (ajout_client, entry115, "entry115");
  GLADE_HOOKUP_OBJECT (ajout_client, label299, "label299");
  GLADE_HOOKUP_OBJECT (ajout_client, label300, "label300");
  GLADE_HOOKUP_OBJECT (ajout_client, label301, "label301");
  GLADE_HOOKUP_OBJECT (ajout_client, label302, "label302");
  GLADE_HOOKUP_OBJECT (ajout_client, spinbutton17, "spinbutton17");
  GLADE_HOOKUP_OBJECT (ajout_client, label303, "label303");
  GLADE_HOOKUP_OBJECT (ajout_client, label304, "label304");
  GLADE_HOOKUP_OBJECT (ajout_client, label305, "label305");
  GLADE_HOOKUP_OBJECT (ajout_client, calendar13, "calendar13");
  GLADE_HOOKUP_OBJECT (ajout_client, label306, "label306");
  GLADE_HOOKUP_OBJECT (ajout_client, button75, "button75");
  GLADE_HOOKUP_OBJECT (ajout_client, alignment58, "alignment58");
  GLADE_HOOKUP_OBJECT (ajout_client, hbox50, "hbox50");
  GLADE_HOOKUP_OBJECT (ajout_client, image54, "image54");
  GLADE_HOOKUP_OBJECT (ajout_client, label350, "label350");
  GLADE_HOOKUP_OBJECT (ajout_client, ajouter_client, "ajouter_client");
  GLADE_HOOKUP_OBJECT (ajout_client, alignment31, "alignment31");
  GLADE_HOOKUP_OBJECT (ajout_client, hbox31, "hbox31");
  GLADE_HOOKUP_OBJECT (ajout_client, image35, "image35");
  GLADE_HOOKUP_OBJECT (ajout_client, label307, "label307");
  GLADE_HOOKUP_OBJECT (ajout_client, label308, "label308");
  GLADE_HOOKUP_OBJECT (ajout_client, combobox8, "combobox8");

  return ajout_client;
}

GtkWidget*
create_modifier_clients (void)
{
  GtkWidget *modifier_clients;
  GtkWidget *fixed72;
  GtkWidget *entry116;
  GtkWidget *entry117;
  GtkWidget *entry118;
  GtkWidget *entry119;
  GtkWidget *label310;
  GtkWidget *label311;
  GtkWidget *label312;
  GtkWidget *label313;
  GtkObject *spinbutton18_adj;
  GtkWidget *spinbutton18;
  GtkWidget *label314;
  GtkWidget *label315;
  GtkWidget *label316;
  GtkWidget *label317;
  GtkWidget *button76;
  GtkWidget *alignment60;
  GtkWidget *hbox51;
  GtkWidget *image55;
  GtkWidget *label352;
  GtkWidget *label318;
  GtkWidget *label319;
  GtkWidget *combobox9;
  GtkWidget *modifier_client;
  GtkWidget *alignment32;
  GtkWidget *hbox32;
  GtkWidget *image36;
  GtkWidget *label320;
  GtkWidget *frame9;
  GtkWidget *alignment59;
  GtkWidget *scrolledwindow7;
  GtkWidget *treeview36;
  GtkWidget *label351;
  GtkWidget *label357;

  modifier_clients = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (modifier_clients), _("Modifier Client"));

  fixed72 = gtk_fixed_new ();
  gtk_widget_show (fixed72);
  gtk_container_add (GTK_CONTAINER (modifier_clients), fixed72);

  entry116 = gtk_entry_new ();
  gtk_widget_show (entry116);
  gtk_fixed_put (GTK_FIXED (fixed72), entry116, 648, 56);
  gtk_widget_set_size_request (entry116, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry116), 8226);

  entry117 = gtk_entry_new ();
  gtk_widget_show (entry117);
  gtk_fixed_put (GTK_FIXED (fixed72), entry117, 648, 248);
  gtk_widget_set_size_request (entry117, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry117), 8226);

  entry118 = gtk_entry_new ();
  gtk_widget_show (entry118);
  gtk_fixed_put (GTK_FIXED (fixed72), entry118, 648, 16);
  gtk_widget_set_size_request (entry118, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry118), 8226);

  entry119 = gtk_entry_new ();
  gtk_widget_show (entry119);
  gtk_fixed_put (GTK_FIXED (fixed72), entry119, 648, 280);
  gtk_widget_set_size_request (entry119, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry119), 8226);

  label310 = gtk_label_new (_("NOM"));
  gtk_widget_show (label310);
  gtk_fixed_put (GTK_FIXED (fixed72), label310, 568, 24);
  gtk_widget_set_size_request (label310, 57, 17);

  label311 = gtk_label_new (_("PRENOM"));
  gtk_widget_show (label311);
  gtk_fixed_put (GTK_FIXED (fixed72), label311, 544, 64);
  gtk_widget_set_size_request (label311, 105, 16);

  label312 = gtk_label_new (_("PASSWORD"));
  gtk_widget_show (label312);
  gtk_fixed_put (GTK_FIXED (fixed72), label312, 544, 280);
  gtk_widget_set_size_request (label312, 113, 25);

  label313 = gtk_label_new (_("LOGIN"));
  gtk_widget_show (label313);
  gtk_fixed_put (GTK_FIXED (fixed72), label313, 576, 256);
  gtk_widget_set_size_request (label313, 57, 17);

  spinbutton18_adj = gtk_adjustment_new (18, 0, 100, 1, 10, 10);
  spinbutton18 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton18_adj), 1, 0);
  gtk_widget_show (spinbutton18);
  gtk_fixed_put (GTK_FIXED (fixed72), spinbutton18, 656, 184);
  gtk_widget_set_size_request (spinbutton18, 60, 27);

  label314 = gtk_label_new (_("Sexe"));
  gtk_widget_show (label314);
  gtk_fixed_put (GTK_FIXED (fixed72), label314, 576, 144);
  gtk_widget_set_size_request (label314, 57, 17);

  label315 = gtk_label_new (_("CIN"));
  gtk_widget_show (label315);
  gtk_fixed_put (GTK_FIXED (fixed72), label315, 576, 104);
  gtk_widget_set_size_request (label315, 57, 17);

  label316 = gtk_label_new (_("Age"));
  gtk_widget_show (label316);
  gtk_fixed_put (GTK_FIXED (fixed72), label316, 576, 192);
  gtk_widget_set_size_request (label316, 57, 17);

  label317 = gtk_label_new (_("Date inscri"));
  gtk_widget_show (label317);
  gtk_fixed_put (GTK_FIXED (fixed72), label317, 552, 224);
  gtk_widget_set_size_request (label317, 113, 16);

  button76 = gtk_button_new ();
  gtk_widget_show (button76);
  gtk_fixed_put (GTK_FIXED (fixed72), button76, 712, 376);
  gtk_widget_set_size_request (button76, 74, 29);

  alignment60 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment60);
  gtk_container_add (GTK_CONTAINER (button76), alignment60);

  hbox51 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox51);
  gtk_container_add (GTK_CONTAINER (alignment60), hbox51);

  image55 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image55);
  gtk_box_pack_start (GTK_BOX (hbox51), image55, FALSE, FALSE, 0);

  label352 = gtk_label_new_with_mnemonic (_("Back"));
  gtk_widget_show (label352);
  gtk_box_pack_start (GTK_BOX (hbox51), label352, FALSE, FALSE, 0);

  label318 = gtk_label_new ("");
  gtk_widget_show (label318);
  gtk_fixed_put (GTK_FIXED (fixed72), label318, 648, 216);
  gtk_widget_set_size_request (label318, 184, 25);

  label319 = gtk_label_new ("");
  gtk_widget_show (label319);
  gtk_fixed_put (GTK_FIXED (fixed72), label319, 648, 96);
  gtk_widget_set_size_request (label319, 152, 25);

  combobox9 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox9);
  gtk_fixed_put (GTK_FIXED (fixed72), combobox9, 648, 136);
  gtk_widget_set_size_request (combobox9, 97, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox9), _("HOMME"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox9), _("FEMME"));

  modifier_client = gtk_button_new ();
  gtk_fixed_put (GTK_FIXED (fixed72), modifier_client, 664, 320);
  gtk_widget_set_size_request (modifier_client, 96, 29);

  alignment32 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment32);
  gtk_container_add (GTK_CONTAINER (modifier_client), alignment32);

  hbox32 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox32);
  gtk_container_add (GTK_CONTAINER (alignment32), hbox32);

  image36 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image36);
  gtk_box_pack_start (GTK_BOX (hbox32), image36, FALSE, FALSE, 0);

  label320 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label320);
  gtk_box_pack_start (GTK_BOX (hbox32), label320, FALSE, FALSE, 0);

  frame9 = gtk_frame_new (NULL);
  gtk_widget_show (frame9);
  gtk_fixed_put (GTK_FIXED (fixed72), frame9, 16, 24);
  gtk_widget_set_size_request (frame9, 528, 336);
  gtk_frame_set_shadow_type (GTK_FRAME (frame9), GTK_SHADOW_NONE);

  alignment59 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment59);
  gtk_container_add (GTK_CONTAINER (frame9), alignment59);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment59), 0, 0, 12, 0);

  scrolledwindow7 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow7);
  gtk_container_add (GTK_CONTAINER (alignment59), scrolledwindow7);

  treeview36 = gtk_tree_view_new ();
  gtk_widget_show (treeview36);
  gtk_container_add (GTK_CONTAINER (scrolledwindow7), treeview36);
  gtk_widget_set_size_request (treeview36, 536, 280);

  label351 = gtk_label_new (_("<b>Liste Client:</b>"));
  gtk_widget_show (label351);
  gtk_frame_set_label_widget (GTK_FRAME (frame9), label351);
  gtk_label_set_use_markup (GTK_LABEL (label351), TRUE);

  label357 = gtk_label_new ("");
  gtk_widget_show (label357);
  gtk_fixed_put (GTK_FIXED (fixed72), label357, 176, 8);
  gtk_widget_set_size_request (label357, 352, 25);

  g_signal_connect_swapped ((gpointer) button76, "clicked",
                            G_CALLBACK (gtk_widget_hide),
                            GTK_OBJECT (modifier_clients));
  g_signal_connect_swapped ((gpointer) button76, "clicked",
                            G_CALLBACK (gtk_widget_show),
                            GTK_OBJECT (window_admin));
  g_signal_connect ((gpointer) modifier_client, "clicked",
                    G_CALLBACK (on_modifier_client_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview36, "row_activated",
                    G_CALLBACK (on_treeview36_row_activated),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modifier_clients, modifier_clients, "modifier_clients");
  GLADE_HOOKUP_OBJECT (modifier_clients, fixed72, "fixed72");
  GLADE_HOOKUP_OBJECT (modifier_clients, entry116, "entry116");
  GLADE_HOOKUP_OBJECT (modifier_clients, entry117, "entry117");
  GLADE_HOOKUP_OBJECT (modifier_clients, entry118, "entry118");
  GLADE_HOOKUP_OBJECT (modifier_clients, entry119, "entry119");
  GLADE_HOOKUP_OBJECT (modifier_clients, label310, "label310");
  GLADE_HOOKUP_OBJECT (modifier_clients, label311, "label311");
  GLADE_HOOKUP_OBJECT (modifier_clients, label312, "label312");
  GLADE_HOOKUP_OBJECT (modifier_clients, label313, "label313");
  GLADE_HOOKUP_OBJECT (modifier_clients, spinbutton18, "spinbutton18");
  GLADE_HOOKUP_OBJECT (modifier_clients, label314, "label314");
  GLADE_HOOKUP_OBJECT (modifier_clients, label315, "label315");
  GLADE_HOOKUP_OBJECT (modifier_clients, label316, "label316");
  GLADE_HOOKUP_OBJECT (modifier_clients, label317, "label317");
  GLADE_HOOKUP_OBJECT (modifier_clients, button76, "button76");
  GLADE_HOOKUP_OBJECT (modifier_clients, alignment60, "alignment60");
  GLADE_HOOKUP_OBJECT (modifier_clients, hbox51, "hbox51");
  GLADE_HOOKUP_OBJECT (modifier_clients, image55, "image55");
  GLADE_HOOKUP_OBJECT (modifier_clients, label352, "label352");
  GLADE_HOOKUP_OBJECT (modifier_clients, label318, "label318");
  GLADE_HOOKUP_OBJECT (modifier_clients, label319, "label319");
  GLADE_HOOKUP_OBJECT (modifier_clients, combobox9, "combobox9");
  GLADE_HOOKUP_OBJECT (modifier_clients, modifier_client, "modifier_client");
  GLADE_HOOKUP_OBJECT (modifier_clients, alignment32, "alignment32");
  GLADE_HOOKUP_OBJECT (modifier_clients, hbox32, "hbox32");
  GLADE_HOOKUP_OBJECT (modifier_clients, image36, "image36");
  GLADE_HOOKUP_OBJECT (modifier_clients, label320, "label320");
  GLADE_HOOKUP_OBJECT (modifier_clients, frame9, "frame9");
  GLADE_HOOKUP_OBJECT (modifier_clients, alignment59, "alignment59");
  GLADE_HOOKUP_OBJECT (modifier_clients, scrolledwindow7, "scrolledwindow7");
  GLADE_HOOKUP_OBJECT (modifier_clients, treeview36, "treeview36");
  GLADE_HOOKUP_OBJECT (modifier_clients, label351, "label351");
  GLADE_HOOKUP_OBJECT (modifier_clients, label357, "label357");

  return modifier_clients;
}

GtkWidget*
create_supprimer_clients (void)
{
  GtkWidget *supprimer_clients;
  GtkWidget *fixed73;
  GtkWidget *frame3;
  GtkWidget *alignment36;
  GtkWidget *scrolledwindow4;
  GtkWidget *treeview37;
  GtkWidget *label326;
  GtkWidget *button77;
  GtkWidget *alignment61;
  GtkWidget *hbox52;
  GtkWidget *image56;
  GtkWidget *label353;
  GtkWidget *supprimer_client;
  GtkWidget *alignment33;
  GtkWidget *hbox33;
  GtkWidget *image37;
  GtkWidget *label322;
  GtkWidget *label358;

  supprimer_clients = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (supprimer_clients), _("Supprimer Client"));
  gtk_window_set_position (GTK_WINDOW (supprimer_clients), GTK_WIN_POS_CENTER);

  fixed73 = gtk_fixed_new ();
  gtk_widget_show (fixed73);
  gtk_container_add (GTK_CONTAINER (supprimer_clients), fixed73);

  frame3 = gtk_frame_new (NULL);
  gtk_widget_show (frame3);
  gtk_fixed_put (GTK_FIXED (fixed73), frame3, 32, 24);
  gtk_widget_set_size_request (frame3, 696, 264);
  gtk_frame_set_shadow_type (GTK_FRAME (frame3), GTK_SHADOW_NONE);

  alignment36 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment36);
  gtk_container_add (GTK_CONTAINER (frame3), alignment36);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment36), 0, 0, 12, 0);

  scrolledwindow4 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow4);
  gtk_container_add (GTK_CONTAINER (alignment36), scrolledwindow4);

  treeview37 = gtk_tree_view_new ();
  gtk_widget_show (treeview37);
  gtk_container_add (GTK_CONTAINER (scrolledwindow4), treeview37);
  gtk_widget_set_size_request (treeview37, 640, 240);

  label326 = gtk_label_new (_("<b>Liste Clients:</b>"));
  gtk_widget_show (label326);
  gtk_frame_set_label_widget (GTK_FRAME (frame3), label326);
  gtk_label_set_use_markup (GTK_LABEL (label326), TRUE);

  button77 = gtk_button_new ();
  gtk_widget_show (button77);
  gtk_fixed_put (GTK_FIXED (fixed73), button77, 720, 336);
  gtk_widget_set_size_request (button77, 74, 29);

  alignment61 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment61);
  gtk_container_add (GTK_CONTAINER (button77), alignment61);

  hbox52 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox52);
  gtk_container_add (GTK_CONTAINER (alignment61), hbox52);

  image56 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image56);
  gtk_box_pack_start (GTK_BOX (hbox52), image56, FALSE, FALSE, 0);

  label353 = gtk_label_new_with_mnemonic (_("Back"));
  gtk_widget_show (label353);
  gtk_box_pack_start (GTK_BOX (hbox52), label353, FALSE, FALSE, 0);

  supprimer_client = gtk_button_new ();
  gtk_widget_show (supprimer_client);
  gtk_fixed_put (GTK_FIXED (fixed73), supprimer_client, 736, 112);
  gtk_widget_set_size_request (supprimer_client, 104, 32);

  alignment33 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment33);
  gtk_container_add (GTK_CONTAINER (supprimer_client), alignment33);

  hbox33 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox33);
  gtk_container_add (GTK_CONTAINER (alignment33), hbox33);

  image37 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image37);
  gtk_box_pack_start (GTK_BOX (hbox33), image37, FALSE, FALSE, 0);

  label322 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label322);
  gtk_box_pack_start (GTK_BOX (hbox33), label322, FALSE, FALSE, 0);

  label358 = gtk_label_new ("");
  gtk_widget_show (label358);
  gtk_fixed_put (GTK_FIXED (fixed73), label358, 224, 8);
  gtk_widget_set_size_request (label358, 352, 25);

  g_signal_connect_swapped ((gpointer) button77, "clicked",
                            G_CALLBACK (gtk_widget_hide),
                            GTK_OBJECT (supprimer_clients));
  g_signal_connect_swapped ((gpointer) button77, "clicked",
                            G_CALLBACK (gtk_widget_show),
                            GTK_OBJECT (window_admin));
  g_signal_connect ((gpointer) supprimer_client, "clicked",
                    G_CALLBACK (on_supprimer_client_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (supprimer_clients, supprimer_clients, "supprimer_clients");
  GLADE_HOOKUP_OBJECT (supprimer_clients, fixed73, "fixed73");
  GLADE_HOOKUP_OBJECT (supprimer_clients, frame3, "frame3");
  GLADE_HOOKUP_OBJECT (supprimer_clients, alignment36, "alignment36");
  GLADE_HOOKUP_OBJECT (supprimer_clients, scrolledwindow4, "scrolledwindow4");
  GLADE_HOOKUP_OBJECT (supprimer_clients, treeview37, "treeview37");
  GLADE_HOOKUP_OBJECT (supprimer_clients, label326, "label326");
  GLADE_HOOKUP_OBJECT (supprimer_clients, button77, "button77");
  GLADE_HOOKUP_OBJECT (supprimer_clients, alignment61, "alignment61");
  GLADE_HOOKUP_OBJECT (supprimer_clients, hbox52, "hbox52");
  GLADE_HOOKUP_OBJECT (supprimer_clients, image56, "image56");
  GLADE_HOOKUP_OBJECT (supprimer_clients, label353, "label353");
  GLADE_HOOKUP_OBJECT (supprimer_clients, supprimer_client, "supprimer_client");
  GLADE_HOOKUP_OBJECT (supprimer_clients, alignment33, "alignment33");
  GLADE_HOOKUP_OBJECT (supprimer_clients, hbox33, "hbox33");
  GLADE_HOOKUP_OBJECT (supprimer_clients, image37, "image37");
  GLADE_HOOKUP_OBJECT (supprimer_clients, label322, "label322");
  GLADE_HOOKUP_OBJECT (supprimer_clients, label358, "label358");

  return supprimer_clients;
}

GtkWidget*
create_login (void)
{
  GtkWidget *login;
  GtkWidget *fixed77;
  GtkWidget *frame6;
  GtkWidget *alignment48;
  GtkWidget *fixed78;
  GtkWidget *entry120;
  GtkWidget *entry121;
  GtkWidget *label339;
  GtkWidget *label340;
  GtkWidget *btn_login;
  GtkWidget *alignment49;
  GtkWidget *hbox43;
  GtkWidget *image47;
  GtkWidget *label341;
  GtkWidget *label338;
  GtkWidget *button69;
  GtkWidget *alignment50;
  GtkWidget *hbox44;
  GtkWidget *image48;
  GtkWidget *label342;
  GtkWidget *label354;

  login = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (login), _("LOGIN"));
  gtk_window_set_position (GTK_WINDOW (login), GTK_WIN_POS_CENTER);

  fixed77 = gtk_fixed_new ();
  gtk_widget_show (fixed77);
  gtk_container_add (GTK_CONTAINER (login), fixed77);

  frame6 = gtk_frame_new (NULL);
  gtk_widget_show (frame6);
  gtk_fixed_put (GTK_FIXED (fixed77), frame6, 24, 40);
  gtk_widget_set_size_request (frame6, 352, 168);
  gtk_container_set_border_width (GTK_CONTAINER (frame6), 2);
  gtk_frame_set_shadow_type (GTK_FRAME (frame6), GTK_SHADOW_OUT);

  alignment48 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment48);
  gtk_container_add (GTK_CONTAINER (frame6), alignment48);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment48), 0, 0, 12, 0);

  fixed78 = gtk_fixed_new ();
  gtk_widget_show (fixed78);
  gtk_container_add (GTK_CONTAINER (alignment48), fixed78);

  entry120 = gtk_entry_new ();
  gtk_widget_show (entry120);
  gtk_fixed_put (GTK_FIXED (fixed78), entry120, 152, 24);
  gtk_widget_set_size_request (entry120, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry120), 8226);

  entry121 = gtk_entry_new ();
  gtk_widget_show (entry121);
  gtk_fixed_put (GTK_FIXED (fixed78), entry121, 152, 72);
  gtk_widget_set_size_request (entry121, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry121), 8226);

  label339 = gtk_label_new (_("LOGIN"));
  gtk_widget_show (label339);
  gtk_fixed_put (GTK_FIXED (fixed78), label339, 48, 32);
  gtk_widget_set_size_request (label339, 57, 17);

  label340 = gtk_label_new (_("Password"));
  gtk_widget_show (label340);
  gtk_fixed_put (GTK_FIXED (fixed78), label340, 48, 80);
  gtk_widget_set_size_request (label340, 88, 17);

  btn_login = gtk_button_new ();
  gtk_widget_show (btn_login);
  gtk_fixed_put (GTK_FIXED (fixed78), btn_login, 200, 112);
  gtk_widget_set_size_request (btn_login, 74, 29);

  alignment49 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment49);
  gtk_container_add (GTK_CONTAINER (btn_login), alignment49);

  hbox43 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox43);
  gtk_container_add (GTK_CONTAINER (alignment49), hbox43);

  image47 = gtk_image_new_from_stock ("gtk-connect", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image47);
  gtk_box_pack_start (GTK_BOX (hbox43), image47, FALSE, FALSE, 0);

  label341 = gtk_label_new_with_mnemonic (_("LOGIN"));
  gtk_widget_show (label341);
  gtk_box_pack_start (GTK_BOX (hbox43), label341, FALSE, FALSE, 0);

  label338 = gtk_label_new (_("<b>INFO:</b>"));
  gtk_widget_show (label338);
  gtk_frame_set_label_widget (GTK_FRAME (frame6), label338);
  gtk_label_set_use_markup (GTK_LABEL (label338), TRUE);

  button69 = gtk_button_new ();
  gtk_widget_show (button69);
  gtk_fixed_put (GTK_FIXED (fixed77), button69, 312, 256);
  gtk_widget_set_size_request (button69, 74, 29);

  alignment50 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment50);
  gtk_container_add (GTK_CONTAINER (button69), alignment50);

  hbox44 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox44);
  gtk_container_add (GTK_CONTAINER (alignment50), hbox44);

  image48 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image48);
  gtk_box_pack_start (GTK_BOX (hbox44), image48, FALSE, FALSE, 0);

  label342 = gtk_label_new_with_mnemonic (_("QUIT"));
  gtk_widget_show (label342);
  gtk_box_pack_start (GTK_BOX (hbox44), label342, FALSE, FALSE, 0);

  label354 = gtk_label_new ("");
  gtk_widget_show (label354);
  gtk_fixed_put (GTK_FIXED (fixed77), label354, 56, 8);
  gtk_widget_set_size_request (label354, 328, 25);

  g_signal_connect ((gpointer) btn_login, "clicked",
                    G_CALLBACK (on_btn_login_clicked),
                    NULL);
  g_signal_connect ((gpointer) button69, "clicked",
                    G_CALLBACK (gtk_main_quit),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (login, login, "login");
  GLADE_HOOKUP_OBJECT (login, fixed77, "fixed77");
  GLADE_HOOKUP_OBJECT (login, frame6, "frame6");
  GLADE_HOOKUP_OBJECT (login, alignment48, "alignment48");
  GLADE_HOOKUP_OBJECT (login, fixed78, "fixed78");
  GLADE_HOOKUP_OBJECT (login, entry120, "entry120");
  GLADE_HOOKUP_OBJECT (login, entry121, "entry121");
  GLADE_HOOKUP_OBJECT (login, label339, "label339");
  GLADE_HOOKUP_OBJECT (login, label340, "label340");
  GLADE_HOOKUP_OBJECT (login, btn_login, "btn_login");
  GLADE_HOOKUP_OBJECT (login, alignment49, "alignment49");
  GLADE_HOOKUP_OBJECT (login, hbox43, "hbox43");
  GLADE_HOOKUP_OBJECT (login, image47, "image47");
  GLADE_HOOKUP_OBJECT (login, label341, "label341");
  GLADE_HOOKUP_OBJECT (login, label338, "label338");
  GLADE_HOOKUP_OBJECT (login, button69, "button69");
  GLADE_HOOKUP_OBJECT (login, alignment50, "alignment50");
  GLADE_HOOKUP_OBJECT (login, hbox44, "hbox44");
  GLADE_HOOKUP_OBJECT (login, image48, "image48");
  GLADE_HOOKUP_OBJECT (login, label342, "label342");
  GLADE_HOOKUP_OBJECT (login, label354, "label354");

  return login;
}

